name: Documentation Test
on:
  push:
    branches: [ "publish-mdbook-live"]
  pull_request:
    branches: [ "publish-mdbook-live"]

jobs:
  mdbook_test:
    name: Test mdBook Documentation builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
      - name: Test mdBook in doc/rayhunter
        run: mdbook test doc/rayhunter
