name: Publish Documentation
on:
  push:
    branches: [ "publish-mdbook-live"]

env:
  MDBOOK_DIR: doc/rayhunter

jobs:
  mdbook_test:
    name: Test mdBook Documentation builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
      - name: Test mdBook
        run: mdbook test $MDBOOK_DIR
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/rayhunter/book
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
